name: Angular - Tests
on:
  push:
    branches: ['develop', 'release-*']
jobs:
  build-angular:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      with: {fetch-depth: 0}
      - uses: actions/setup-node@v1
        with:
          node-version: 16
      - run: npm ci
      - run: npm run-script build-prod
        
